# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
name: just-create-change

on: 
  workflow_dispatch:
    inputs:
       start_date:        
         description: 'Change Start Date'
         required: true
         default: 'YYYY-MM-DDHH:MM:SS'
       end_date:
         description: 'Change End Date'
         required: true
         default: 'YYYY-MM-DDHH:MM:SS'

permissions:
  contents: read

jobs:
  servicenow-change:
    name: Change Acceleration 
    runs-on: ubuntu-latest
   # needs: servicenow-artifact 
    steps:
      - name: ServiceNow DevOps Change
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
          #devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          devops-integration-user-name: ${{secrets.SN_DEVOPS_USER}}
          devops-integration-user-password: ${{secrets.SN_DEVOPS_PWD}}
          instance-url: ${{secrets.SNOW_DEVOPS_URL}}
          tool-id: ${{secrets.SNOW_DEVOPS_TOOLID}}
          context-github: ${{ toJSON(github) }}
          job-name: 'Change Acceleration'
          #change-request: '{"setCloseCode":"true","attributes":{"start_date":"${{ github.event.inputs.start_date }}","end_date":"${{ github.event.inputs.end_date }}","correlation_id":"gh_${{ github.repository }}-${{ github.workflow }}.${{ github.run_number }}.${{ github.run_attempt }}","short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          #change-request: '{"setCloseCode" : true,"attributes": {"requested_by": {"name": "DevOps Integration User"},"assignment_group": {"name": "ServiceNow Support"},"assigned_to": {"name": "DevOps Integration User"},"cmdb_ci": {"name": "ServiceNow ITSM F4F"},"service_offering": {"name": "ALL::ServiceNow Support"},"business_service": {"name": "Global Functions IT"},"chg_model": "dfeedc6c87688110c3d4851d8bbb3570","category": "Project","start_date":"${{ inputs.start_date }}","end_date":"${{ inputs.end_date }})","correlation_id":"gh_${{ github.repository }}-${{ github.workflow }}.${{ github.run_number }}.${{ github.run_attempt }}","short_description":"test-devops","description":"test-devops","implementation_plan":"test","backout_plan":"test","test_plan":"test"}}'
          change-request: '{"setCloseCode":"true","attributes":{"test_plan":"failure","type":"normal","chg_model": "007c4001c343101035ae3f52c1d3aeb2","start_date":"${{ github.event.inputs.start_date }}","end_date":"${{ github.event.inputs.end_date }}","correlation_id":"gh_${{ github.repository }}-${{ github.workflow }}.${{ github.run_number }}.${{ github.run_attempt }}","template":"ee7afdcd473321100519249bd36d43b8"}}'
          interval: '100'
          timeout: '3600'
          changeCreationTimeOut: '3600' # optional, default is 3600
          abortOnChangeCreationFailure: true # optional, default is true
          abortOnChangeStepTimeout: true # optional, default is true
          #deployment-gate: '{"environment":"deploymentgate","jobName":"Change Acceleration"}'
