name: first-wf
'on': workflow_dispatch
jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://dev65554.service-now.com/api/now/table/incident/8d6353eac0a8016400d8a125ca14fc1f'
        method: 'GET'
        username: 'RestUser'
        password: 'BhindiBhaja@1'
        customHeaders: '{"Content-Type": "application/json"}'
        //data: '{"key_1": "value_1", "key_2": "value_2"}'
    
    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with: 
       url: 'https://dev65554.service-now.com/api/now/table/incident/8d6353eac0a8016400d8a125ca14fc1f'
      
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
